/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "message.pb-c.h"
void   calc_message__init
                     (CalcMessage         *message)
{
  static CalcMessage init_value = CALC_MESSAGE__INIT;
  *message = init_value;
}
size_t calc_message__get_packed_size
                     (const CalcMessage *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &calc_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t calc_message__pack
                     (const CalcMessage *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &calc_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t calc_message__pack_to_buffer
                     (const CalcMessage *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &calc_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CalcMessage *
       calc_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CalcMessage *)
     protobuf_c_message_unpack (&calc_message__descriptor,
                                allocator, len, data);
}
void   calc_message__free_unpacked
                     (CalcMessage *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &calc_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor calc_message__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CalcMessage, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CalcMessage, msg),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    PROTOBUF_C_OFFSETOF(CalcMessage, has_num),
    PROTOBUF_C_OFFSETOF(CalcMessage, num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned calc_message__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = msg */
  2,   /* field[2] = num */
};
static const ProtobufCIntRange calc_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor calc_message__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "CalcMessage",
  "CalcMessage",
  "CalcMessage",
  "",
  sizeof(CalcMessage),
  3,
  calc_message__field_descriptors,
  calc_message__field_indices_by_name,
  1,  calc_message__number_ranges,
  (ProtobufCMessageInit) calc_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
